name: Test
on:
  workflow_dispatch:

jobs:
  calculate-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v7.1.4


      - name: Run script
        env:
          CUSTOM_CONFIG: ${{ secrets.CUSTOM_CONFIG }}
        run: |
          export DEBUG=true
          if [ -z "$CUSTOM_CONFIG" ]; then
            echo "CUSTOM_CONFIG secret is empty or not set."
            exit 1
          fi
          printf "%b\n" "$CUSTOM_CONFIG" > config/custom.yaml
          echo "CUSTOM_CONFIG loaded into config/custom.yaml"
          uv run src/zotero_arxiv_daily/main.py
